{
 "title": "Actual versus Predicted",
 "description": "The actual values versus predicted values in the model",
 "time": { "from": "2013-01-01T00:00:00.000Z", "to": "2014-01-01T00:00:00.000Z" },
 "panels": [
  {
   "title": "Consumption Actual vs Predicted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(date_consumption) as time,\r\n  general_power_supply as Actual_consumption,\r\n  'general_power_supply' as metric\r\n FROM Consumption_Actual_Predicted\r\nWHERE $__timeFilter(date_consumption)\r\nORDER BY date_consumption ASC;"
    },
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(date_consumption) as time,\r\n  pred_general_power_supply as Predicted_consumption,\r\n  'pred_general_power_supply' as metric\r\n FROM Consumption_Actual_Predicted\r\nWHERE $__timeFilter(date_consumption)\r\nORDER BY date_consumption ASC;"
    }
   ]
  },
  {
   "title": "Solar Actual vs Predicted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(date_solar) as time,\r\n  power_out_kwh as Actual_Solar_Output,\r\n  'power_out_kwh' as metric\r\n FROM Solar_Actual_Predicted\r\nWHERE $__timeFilter(date_solar)\r\nORDER BY date_solar ASC;"
    },
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(date_solar) as time,\r\n  pred_power_out_kwh as Predicted_Solar_Output,\r\n  'pred_power_out_kwh' as metric\r\n FROM Solar_Actual_Predicted\r\nWHERE $__timeFilter(date_solar)\r\nORDER BY date_solar ASC;"
    }
   ]
  },
  {
   "title": "Wind Actual vs Predicted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(date_wind) as time,\r\n  y_true as Actual_Wind_Output,\r\n  'y_true' as metric\r\n FROM Wind_Actual_Predicted\r\nWHERE $__timeFilter(date_wind)\r\nORDER BY date_wind ASC;"
    },
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(date_wind) as time,\r\n  y_pred as Predicted_Wind_Output,\r\n  'y_pred' as metric\r\n FROM Wind_Actual_Predicted\r\nWHERE $__timeFilter(date_wind)\r\nORDER BY date_wind ASC;"
    }
   ]
  }
 ]
}