{
 "title": "Solar Power Dashboard",
 "description": "Contains visualization of the solar power dataset",
 "time": { "from": "2013-03-31T21:00:00.000Z", "to": "2018-06-30T21:00:00.000Z" },
 "panels": [
  {
   "title": "Solar Power Generation (Individual Unit)",
   "type": "graph",
   "description": "Shows the power generation through Solar energy based on weather factors within the date range for an individual unit",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Date) as time,\r\n  power_out_kwh as power_generated,\r\n  'power_out_kwh' as metric\r\n FROM calculated_dataset_solar\r\nWHERE $__timeFilter(Date)\r\nORDER BY Date ASC"
    }
   ]
  },
  {
   "title": "Solar Power Generation (Entire Farm)",
   "type": "graph",
   "description": "Shows the power generation through Solar energy based on weather factors within the date range for the Entire Farm",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Date) as time,\r\n  power_out_farm_kwh as value,\r\n  'power_out_farm_kwh' as metric\r\n FROM calculated_dataset_solar\r\nWHERE $__timeFilter(Date)\r\nORDER BY Date ASC"
    }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "graph",
   "description": "Shows the Air Temperature data related to Solar energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Date) as time,\r\n  Air_Temperature as value,\r\n  'Air_Temperature' as metric\r\n FROM calculated_dataset_solar\r\nWHERE $__timeFilter(Date)\r\nORDER BY Date ASC"
    }
   ]
  },
  {
   "title": "Wind Speed Rate",
   "type": "graph",
   "description": "Shows the Wind Speed rate data related to Solar energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "accMS2" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Date) as time,\r\n  Wind_Speed_at_3m as value,\r\n  'Wind_Speed_at_3m' as metric\r\n FROM calculated_dataset_solar\r\nWHERE $__timeFilter(Date)\r\nORDER BY Date ASC"
    }
   ]
  },
  {
   "title": "Direct Horizontal Irradiation (DHI)",
   "type": "graph",
   "description": "Shows the Direct Horizontal Irradiation (DHI) data related to Solar energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "Wm2" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Date) as time,\r\n  DHI as value,\r\n  'DHI' as metric\r\n FROM calculated_dataset_solar\r\nWHERE $__timeFilter(Date)\r\nORDER BY Date ASC"
    }
   ]
  },
  {
   "title": "Direct Horizontal Irradiation (DHI)",
   "type": "graph",
   "description": "Shows the Direct Horizontal Irradiation (DHI) data related to Solar energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "Wm2" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Date) as time,\r\n  DHI as value,\r\n  'DHI' as metric\r\n FROM calculated_dataset_solar\r\nWHERE $__timeFilter(Date)\r\nORDER BY Date ASC"
    }
   ]
  },
  {
   "title": "Relative Humidity",
   "type": "graph",
   "description": "Shows the Relative Humidity data related to Solar energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Date) as time,\r\n  Relative_Humidity as value,\r\n  'Relative_Humidity' as metric\r\n FROM calculated_dataset_solar\r\nWHERE $__timeFilter(Date)\r\nORDER BY Date ASC"
    }
   ]
  },
  {
   "title": "Barometric Pressure",
   "type": "graph",
   "description": "Shows the Barometric Pressure data related to Solar energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "pressurembar" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(Date) as time,\r\n  Barometric_Pressure as value,\r\n  'Barometric_Pressure' as metric\r\n FROM calculated_dataset_solar\r\nWHERE $__timeFilter(Date)\r\nORDER BY Date ASC"
    }
   ]
  }
 ]
}