{
 "title": "Wind Power Dashboard",
 "description": "Contains visualization of the wind power dataset",
 "time": { "from": "2012-12-31T21:00:00.000Z", "to": "2020-01-01T11:39:08.000Z" },
 "panels": [
  {
   "title": "Wind Power Generation",
   "type": "graph",
   "description": "Shows the power generation through Wind energy based on weather factors within the date range",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(observation_date) as time,\r\n  power_out_kw as power_generated,\r\n  'power_out_kw' as metric\r\n FROM Saud_Wind_power_calculatated_data\r\nWHERE $__timeFilter(observation_date)\r\nORDER BY observation_date ASC"
    }
   ]
  },
  {
   "title": "Wind Speed Rate",
   "type": "graph",
   "description": "Shows the Wind Speed Rate data related to Wind energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "accMS2" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(observation_date) as time,\r\n  wind_speed_rate as value,\r\n  'wind_speed_rate' as metric\r\n FROM Saud_Wind_power_calculatated_data\r\nWHERE $__timeFilter(observation_date)\r\nORDER BY observation_date ASC"
    }
   ]
  },
  {
   "title": "Air Temperature",
   "type": "graph",
   "description": "Shows the Air Temperature data related to Wind energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(observation_date) as time,\r\n  air_temperature as value,\r\n  'air_temperature' as metric\r\n FROM Saud_Wind_power_calculatated_data\r\nWHERE $__timeFilter(observation_date)\r\nORDER BY observation_date ASC"
    }
   ]
  },
  {
   "title": "Sky Ceiling Height",
   "type": "heatmap",
   "description": "Shows the Sky Ceiling Height data related to Wind energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(observation_date) as time,\r\n  sky_ceiling_height as value,\r\n  'sky_ceiling_height' as metric\r\n FROM Saud_Wind_power_calculatated_data\r\nWHERE $__timeFilter(observation_date)\r\nORDER BY observation_date ASC"
    }
   ]
  },
  {
   "title": "Atmospheric Sea Level Pressure",
   "type": "graph",
   "description": "Shows the Atmospheric Sea Level Pressure data related to Wind energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(observation_date) as time,\r\n  atmospheric_sea_level_pressure as value,\r\n  'atmospheric_sea_level_pressure' as metric\r\n FROM Saud_Wind_power_calculatated_data\r\nWHERE $__timeFilter(observation_date)\r\nORDER BY observation_date ASC"
    }
   ]
  },
  {
   "title": "Visibility Distance",
   "type": "graph",
   "description": "Shows the Visibility Distance data related to Wind energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(observation_date) as time,\r\n  visibility_distance as value,\r\n  'visibility_distance' as metric\r\n FROM Saud_Wind_power_calculatated_data\r\nWHERE $__timeFilter(observation_date)\r\nORDER BY observation_date ASC"
    }
   ]
  },
  {
   "title": "Air Temperature Dew Point",
   "type": "graph",
   "description": "Shows the Air Temperature Dew Point data related to Wind energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(observation_date) as time,\r\n  air_temperature_dew_point as value,\r\n  'air_temperature_dew_point' as metric\r\n FROM Saud_Wind_power_calculatated_data\r\nWHERE $__timeFilter(observation_date)\r\nORDER BY observation_date ASC"
    }
   ]
  },
  {
   "title": "Elevation",
   "type": "graph",
   "description": "Shows the elevation data related to Wind energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(observation_date) as time,\r\n  elevation as value,\r\n  'elevation' as metric\r\n FROM Saud_Wind_power_calculatated_data\r\nWHERE $__timeFilter(observation_date)\r\nORDER BY observation_date ASC"
    }
   ]
  },
  {
   "title": "Wind Direction Angle",
   "type": "graph",
   "description": "Shows the Wind Direction Angle data related to Wind energy within the date range",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "degree" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(observation_date) as time,\r\n  wind_direction_angle as value,\r\n  'wind_direction_angle' as metric\r\n FROM Saud_Wind_power_calculatated_data\r\nWHERE $__timeFilter(observation_date)\r\nORDER BY observation_date ASC"
    }
   ]
  },
  {
   "title": "Air Density",
   "type": "graph",
   "description": "Shows the Air Density data related to Wind energy within the date range",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "m3" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\r\n  UNIX_TIMESTAMP(observation_date) as time,\r\n  air_density as value,\r\n  'air_density' as metric\r\n FROM Saud_Wind_power_calculatated_data\r\nWHERE $__timeFilter(observation_date)\r\nORDER BY observation_date ASC\r\n"
    }
   ]
  }
 ]
}